src/aosm/azext_aosm/_configuration.py, src/aosm/azext_aosm/_constants.py, src/aosm/azext_aosm/_params.py, src/aosm/azext_aosm/custom.py, src/aosm/azext_aosm/generate_nfd/cnf_nfd_generator.py, src/aosm/azext_aosm/generate_nfd/nfd_generator_base.py, src/aosm/azext_aosm/generate_nfd/vnf_nfd_generator.py
---
VNF NFD Generation and some refactor
=> VNF NFD generator

src/aosm/README.md
Add some useful information to the readme. Nothing fancy.
=> Update readme with install/bug reporting instructions

src/aosm/azext_aosm/_configuration.py, src/aosm/azext_aosm/_constants.py, src/aosm/azext_aosm/custom.py, src/aosm/azext_aosm/generate_nfd/cnf_nfd_generator.py, src/aosm/azext_aosm/generate_nfd/nfd_generator_base.py, src/aosm/azext_aosm/generate_nfd/vnf_nfd_generator.py, src/aosm/azext_aosm/publisher_resources/publisher_resources.py, src/aosm/azext_aosm/test.py
=> Draft create NFDV using python SDK

src/aosm/HISTORY.rst, src/aosm/README.md, src/aosm/azext_aosm/_params.py, src/aosm/azext_aosm/commands.py, src/aosm/azext_aosm/custom.py, src/aosm/azext_aosm/generate_nfd/vnf_bicep_nfd_generator.py, src/aosm/setup.py
I want to get these in before I send the commands to the CLI review.
Others should be aware of these changes to avoid merge problems.
=> Refactor commands to az aosm nfd|nsd build

src/aosm/setup.py
=> added templates to setup.py

src/aosm/azext_aosm/_configuration.py, src/aosm/azext_aosm/custom.py, src/aosm/azext_aosm/generate_nfd/cnf_nfd_generator.py, src/aosm/azext_aosm/generate_nfd/vnf_nfd_generator.py
PR includes:
- adding meaningful logs
- error handling for not providing parameters in ARM template
- preventing auto overwriting of input.json
- adding clarifying comments to help text
- convert vnf types in schema
---
=> Improve CLI based on Feedback

src/aosm/azext_aosm/deploy/deploy_with_arm.py, src/aosm/azext_aosm/generate_nfd/templates/cnfartifactmanifest.bicep.j2, src/aosm/azext_aosm/generate_nfd/templates/cnfdefinition.bicep.j2, src/aosm/azext_aosm/generate_nfd/templates/vnfartifactmanifests.bicep, src/aosm/azext_aosm/generate_nfd/templates/vnfdefinition.bicep
=> Fix wrong location creation bug

src/aosm/README.md, src/aosm/azext_aosm/_configuration.py, src/aosm/azext_aosm/generate_nfd/cnf_nfd_generator.py
added path_to_mappings to input.json; added logic to take mappings from file outside of helm package
---
=> Move Value Mappings to Outside Helm Package

src/aosm/azext_aosm/generate_nfd/templates/cnfdefinition.bicep.j2
=> fix CNF depends on

src/aosm/azext_aosm/generate_nfd/cnf_nfd_generator.py
---
Removing forgotten print statement
=> removing print statement

src/aosm/azext_aosm/_configuration.py, src/aosm/azext_aosm/custom.py, src/aosm/azext_aosm/generate_nfd/cnf_nfd_generator.py, src/aosm/azext_aosm/generate_nsd/nsd_generator.py, src/aosm/azext_aosm/generate_nsd/templates/artifact_manifest_template.bicep, src/aosm/azext_aosm/generate_nsd/templates/nf_template.bicep
---
- Fix NF template that is an artifact for NSDs to have the correct nfviType
- Fix discrepancy between parameter types in deploymentValues and bicep templates
- Fix some linting - all the changes in cnf_nfd_generator.py are linting changes
- Rework NSD code so all the logic for it is mainly within the generate_nsd.py class
- Change artifact type for NF template to ArmTemplate, which is what it is
Note that I am getting ORAS errors on Artifact upload, I don't think they are to do with these fixes, so want to investigate separately
=> Nsd for cnfs

src/aosm/azext_aosm/generate_nfd/vnf_nfd_generator.py
=> fix vnf deploy schema types

src/aosm/README.md, src/aosm/development.md
Update README with information about how to use logging.
=> Update README with logging info

src/aosm/HISTORY.rst, src/aosm/setup.py
=> Take oras 0.1.19 to fix Windows artifact upload

src/aosm/azext_aosm/deploy/deploy_with_arm.py, src/aosm/azext_aosm/tests/latest/recording_processors.py, src/aosm/azext_aosm/tests/latest/recordings/test_vnf_nsd_publish_and_delete.yaml, src/aosm/azext_aosm/tests/latest/scenario_test_mocks/mock_input_templates/cnf_input_template.json, src/aosm/azext_aosm/tests/latest/scenario_test_mocks/mock_input_templates/cnf_nsd_input_template.json, src/aosm/azext_aosm/tests/latest/test_aosm_cnf_publish_and_delete.py, src/aosm/azext_aosm/tests/latest/test_aosm_vnf_publish_and_delete.py, src/aosm/development.md
Copy of this PR: https://github.com/jddarby/azure-cli-extensions/pull/67
=> Fix integration tests (#67)

src/aosm/HISTORY.rst, src/aosm/azext_aosm/deploy/deploy_with_arm.py, src/aosm/azext_aosm/tests/latest/recordings/test_vnf_nsd_publish_and_delete.yaml
Duplicate of https://github.com/jddarby/azure-cli-extensions/pull/62
=> move artifact upload to before nfd/nsd deploy (#62)

src/aosm/azext_aosm/_configuration.py, src/aosm/azext_aosm/custom.py, src/aosm/azext_aosm/delete/delete.py, src/aosm/azext_aosm/deploy/deploy_with_arm.py, src/aosm/azext_aosm/deploy/pre_deploy.py
---
Tested build, publish and delete commands still work.
=> Renamed nsdg to nsd

src/aosm/azext_aosm/deploy/pre_deploy.py
-Prerelease version of 4ebc39db638349c3c02a09fd1089287cbbc7d544
=> revert bad markup (#94)

src/aosm/HISTORY.rst, src/aosm/azext_aosm/deploy/artifact.py, src/aosm/azext_aosm/deploy/deploy_with_arm.py
Pre-release version of 8795b8742515557dd3d4d5a372b455cffbc6d339
=> Fix cnf image take 2 (#101)

src/aosm/azext_aosm/_configuration.py, src/aosm/azext_aosm/generate_nfd/cnf_nfd_generator.py
* added default rg and acr values for nf + nsd; added blob_url default for vnf
* added bug fix to close Paulo's bug
* change error message back
---------
---
=> Default RG and ACR Values with Publisher Name (#103)

src/aosm/HISTORY.rst, src/aosm/azext_aosm/generate_nfd/cnf_nfd_generator.py
Pre-release version of https://github.com/jddarby/azure-cli-extensions/pull/107
=> Pre release list parse fix

src/aosm/azext_aosm/deploy/artifact.py
Fix the bug from this thread: https://teams.microsoft.com/l/message/19:feca2556f4b34689adb54f456368aa86@thread.tacv2/1691072162429?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=48260c72-f4d1-447a-b044-72652b1c2580&parentMessageId=1691072162429&teamName=A4O%20Technical%20Team&channelName=AOSM%20Help&createdTime=1691072162429
=> Fix unauthorized error bug

src/aosm/HISTORY.rst, src/aosm/azext_aosm/generate_nfd/cnf_nfd_generator.py, src/aosm/azext_aosm/generate_nfd/templates/cnfdefinition.bicep.j2
Prerelease version of 2779e8ededa90d85cc33b9fac00f9e3a7d70ad75
=> Pre release format helm names

src/aosm/azext_aosm/deploy/artifact.py
=> Fix error parsing

src/aosm/HISTORY.rst, src/aosm/azext_aosm/_configuration.py, src/aosm/azext_aosm/generate_nfd/cnf_nfd_generator.py
pre-release version of 848ee2e2f394998787bacbef4ed8e80dcaee8783
=> Pre release lower case acr

src/aosm/azext_aosm/_params.py, src/aosm/azext_aosm/custom.py
=> Markups from the CLI team

src/aosm/azext_aosm/build_processors/base_processor.py
=> DeployParams fix

src/aosm/azext_aosm/configuration_models/onboarding_base_input_config.py
=> Changed Comment for RG in Config

src/aosm/HISTORY.rst, src/aosm/setup.py
=> bumped version and updated changelog

src/aosm/HISTORY.rst, src/aosm/azext_aosm/common/templates/nsd/nf_template.bicep.j2
---
- changed configuration type from secret to open; 
- updated changelog
=> Changed configuration type from secret to open

src/aosm/HISTORY.rst, src/aosm/setup.py
Reverts jddarby/azure-cli-extensions#164
This change breaks the wheel build in windows
=> Revert "Add docker dependency option to oras in setup.py"

src/aosm/HISTORY.rst, src/aosm/setup.py
=> Bump Version for Public Release of CLI

src/aosm/HISTORY.rst, src/aosm/setup.py
=> Bumped Version to 2.0.0b

src/aosm/azext_aosm/_help.py, src/aosm/azext_aosm/_params.py, src/aosm/azext_aosm/tests/latest/integration_tests/scenario_tests/recordings/test_vnf_nsd_build_and_publish.yaml
=> Fix linting + tests for release

src/aosm/azext_aosm/cli_handlers/onboarding_nsd_handler.py, src/aosm/azext_aosm/common/templates/nsd/nf_template.bicep.j2, src/aosm/azext_aosm/common/templates/nsd/nsddefinition.bicep.j2, src/aosm/azext_aosm/configuration_models/onboarding_nsd_input_config.py, src/aosm/azext_aosm/inputs/nfd_input.py, src/aosm/azext_aosm/tests/latest/integration_tests/integration_test_mocks/mock_input_templates/input_multi_nf_nsd.jsonc, src/aosm/azext_aosm/tests/latest/integration_tests/integration_test_mocks/mock_input_templates/input_multiple_instances.jsonc, src/aosm/azext_aosm/tests/latest/integration_tests/integration_test_mocks/mock_input_templates/nsd_core_input.jsonc, src/aosm/azext_aosm/tests/latest/integration_tests/integration_test_mocks/mock_input_templates/vnf_nsd_input_template.jsonc, src/aosm/azext_aosm/tests/latest/integration_tests/nsd_output/test_build/artifacts/ubuntu-vm.bicep, src/aosm/azext_aosm/tests/latest/integration_tests/nsd_output/test_build/nsdDefinition/config-group-schema.json, src/aosm/azext_aosm/tests/latest/integration_tests/nsd_output/test_build/nsdDefinition/deploy.bicep, src/aosm/azext_aosm/tests/latest/integration_tests/nsd_output/test_build/nsdDefinition/ubuntu-mappings.json, src/aosm/azext_aosm/tests/latest/integration_tests/nsd_output/test_build_multiple_instances/artifacts/ubuntu-vm.bicep, src/aosm/azext_aosm/tests/latest/integration_tests/nsd_output/test_build_multiple_instances/nsdDefinition/config-group-schema.json, src/aosm/azext_aosm/tests/latest/integration_tests/nsd_output/test_build_multiple_instances/nsdDefinition/deploy.bicep, src/aosm/azext_aosm/tests/latest/integration_tests/nsd_output/test_build_multiple_instances/nsdDefinition/ubuntu-mappings.json, src/aosm/azext_aosm/tests/latest/integration_tests/scenario_tests/recordings/test_cnf_nfd_build_and_publish.yaml, src/aosm/azext_aosm/tests/latest/integration_tests/scenario_tests/recordings/test_vnf_nsd_build_and_publish.yaml, src/aosm/azext_aosm/tests/latest/integration_tests/test_nsd.py
NOTE: ANDY HAS REVIEWED FIRST 3 BUGS ALREADY. THIS REVIEW SHOULD FOCUS ON NFVISFROMSITE CHANGES.
NFVIFromSite Change:
- Each nfdv directly maps to an nfviFromSite object
- Added loop in template to have unique names and keys
- If all nfvi types are azure core, only have one nfviFromSite object
- 
After nsd publish, looks like this for multiple nfs:
{
"nfvi1": {
"name": "jl-testnfvis-nsd_NFVI1",
"type": "AzureArcKubernetes"
},
"nfvi2": {
"name": "jl-testnfvis-nsd_NFVI2",
"type": "AzureArcKubernetes"
}
}
---
- renamed nfdvName to nfdv:
- 
Below image shows 2 of the changes:
- additional comment above RET list
- additional comment above name
There is a pipeline to automatically …
=> Fix minor config bugs

src/aosm/azext_aosm/_help.py, src/aosm/azext_aosm/_params.py
Some additional help text as required by the CLI team.
See checklist at the bottom of this doc for what's required. Note the TOC stuff mentioned there is (apparently) already covered, so this PR only covers the long summary, parameters and examples.
=> Help text additions

src/aosm/azext_aosm/_params.py
=> Fix lines too long

src/aosm/HISTORY.rst
=> updated changelog

src/aosm/azext_aosm/aaz/latest/aosm/__cmd_group.py, src/aosm/azext_aosm/aaz/latest/aosm/publisher/__cmd_group.py, src/aosm/azext_aosm/aaz/latest/aosm/publisher/artifact_manifest/__cmd_group.py, src/aosm/azext_aosm/aaz/latest/aosm/publisher/artifact_manifest/_list.py, src/aosm/azext_aosm/aaz/latest/aosm/publisher/artifact_manifest/_list_credential.py, src/aosm/azext_aosm/aaz/latest/aosm/publisher/artifact_manifest/_update_state.py, src/aosm/azext_aosm/aaz/latest/aosm/publisher/artifact_store/artifact/_list.py, src/aosm/azext_aosm/aaz/latest/aosm/publisher/artifact_store/artifact/version/_list.py, src/aosm/azext_aosm/aaz/latest/aosm/publisher/artifact_store/artifact/version/_update_state.py, src/aosm/azext_aosm/aaz/latest/aosm/publisher/configuration_group_schema/_list.py, src/aosm/azext_aosm/aaz/latest/aosm/publisher/configuration_group_schema/_update_state.py, src/aosm/azext_aosm/aaz/latest/aosm/publisher/network_function_definition/version/_list.py, src/aosm/azext_aosm/aaz/latest/aosm/publisher/network_function_definition/version/_update_state.py, src/aosm/azext_aosm/aaz/latest/aosm/publisher/network_service_design/version/_list.py, src/aosm/azext_aosm/aaz/latest/aosm/publisher/network_service_design/version/_update_state.py
- Add examples
- Minor rewording
- Ensure all commands are preview
---
=> Autogen CLI:

src/aosm/azext_aosm/inputs/helm_chart_input.py
=> Refactor HelmChartInput.from_chart_path()

src/aosm/azext_aosm/cli_handlers/onboarding_sns_handler.py
=> Resolving style error

src/aosm/azext_aosm/tests/latest/integration_tests/scenario_tests/recordings/test_vnf_nsd_build_and_publish.yaml
Re record test to try to fix the pipeline
=> Re-record test

src/aosm/azext_aosm/tests/latest/integration_tests/scenario_tests/recordings/test_vnf_nsd_build_and_publish.yaml
=> Fixed VNF Recording
