jddarby/azure-cli-extensions

src/aosm/azext_aosm/delete/__init__.py, src/aosm/azext_aosm/deploy/__init__.py, src/aosm/azext_aosm/generate_nfd/__init__.py, src/aosm/azext_aosm/util/__init__.py
After installing from the packaged wheel, any attempts to use commands beneath the top level "aosm" currently fail, because the submodules can't be found within the extension. This includes help commands:
```
developer@Ephemera:~$ az aosm definition --help
The command failed with an unexpected error. Here is the traceback:
No module named 'azext_aosm.generate_nfd'
```
A lengthy stack trace also follows, but the key thing here is that `generate_nfd` is not found within `azext_aosm`.
This is because when building the list of packages to include we use `setuptools`, specifically the `find_packages()` function, which doesn't recognise this as a valid submodule because it lacks an `__init__.py`. The same is true of other modules within the extension, this just happens to be the one we hit …
=> Add empty init files to inner modules so setuptools recognises them

src/aosm/azext_aosm/deploy/pre_deploy.py
azure.mgmt.resource provides a generic set of models (which just uses the set from the latest version available). Move to use that instead of a specific model for Resource Group creation because otherwise we depend on a specific minimum version (where we haven't declared a specific dependency), despite not actually using any version-specific properties.
=> Use latest RG model to remove unnecessary dependency on version

src/aosm/azext_aosm/deploy/deploy_with_arm.py
Just like with RGs, use the azure.mgmt.resource generic set of models (which just uses the set from the latest version available) instead of a specific model for Deployment creation because otherwise we depend on a specific minimum version (where we haven't declared a specific dependency), despite not actually using any version-specific properties.
=> Use latest Deployment model to remove unnecessary dependency on version

src/aosm/azext_aosm/_configuration.py, src/aosm/azext_aosm/deploy/artifact.py, src/aosm/azext_aosm/deploy/artifact_manifest.py, src/aosm/azext_aosm/deploy/deploy_with_arm.py, src/aosm/azext_aosm/generate_nfd/templates/vnfartifactmanifests.bicep, src/aosm/azext_aosm/generate_nsd/nsd_generator.py
Fix for https://dev.azure.com/msazuredev/AzureForOperators/_workitems/edit/735056
This PR fixes three things:
- A different name for the VHD artifact was used in different places.  This PR makes them consistent and of the form {nf-name}-vhd.  Therefore we no longer ask the user to supply an artifact name.
- When the VHD is uploaded to blob store the blob name must end in ".vhd"
- When the VHD is uploaded to blob store it must be uploaded as a page blob.
I haven't actually managed to get as far as deploying the SNS, as I was testing with a vnet ARM template and supplying an empty VHD.  It turns out that isn't allowed.
---
There is a pipeline to automatically build, upload and …
=> Name uploaded VHD correctly

src/aosm/azext_aosm/deploy/artifact.py
Small fix for broken ORAS target string.
Original error seen:
```
The command failed with an unexpected error. Here is the traceback:
HTTPSConnectionPool(host='ac4mitestingac4mitestingacred058481d7.azurecr.io%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20', port=443):
```
Those `%20`s are spaces that have crept in.
=> Fix for oras target string with erroneous spaces

src/aosm/HISTORY.rst, src/aosm/azext_aosm/deploy/artifact.py, src/aosm/setup.md
Workaround for https://github.com/oras-project/oras-py/issues/90 to fix Artifact upload when running on Windows. 
This can be reverted when https://github.com/oras-project/oras-py/pull/91 is released and oras is bumped.
=> Fix Artifact upload on Windows

src/aosm/HISTORY.rst, src/aosm/README.md, src/aosm/azext_aosm/_configuration.py, src/aosm/azext_aosm/generate_nfd/cnf_nfd_generator.py, src/aosm/azext_aosm/generate_nsd/nsd_generator.py, src/aosm/azext_aosm/generate_nsd/templates/nf_template.bicep.j2, src/aosm/azext_aosm/tests/latest/metaschema.json, src/aosm/azext_aosm/tests/latest/metaschema_modified.json, src/aosm/azext_aosm/tests/latest/mock_nsd/input_multiple_instances.json, src/aosm/azext_aosm/tests/latest/test_nsd.py, src/aosm/azext_aosm/tests/latest/test_vnf.py
This PR adds an option to create an NSD where the operator can specify how many copies of an NF they want to deploy and the configuration for each of them.
I tested and unfortunately there is a bug that mean that this doesn't work for CNFs: https://portal.microsofticm.com/imp/v3/incidents/details/405078667/home
This PR shouldn't be updated until corresponding changes are made to the quickstarts.
=> Multiple NFs of the same type

src/aosm/azext_aosm/_params.py, src/aosm/azext_aosm/custom.py, src/aosm/azext_aosm/deploy/deploy_with_arm.py, src/aosm/azext_aosm/util/constants.py
- Moved variables onto the class instance and stop passing them around in the method signatures
- Also made the deployer class a dataclass for cleaner \_\_init\_\_
- Made `parameters` a property of the class, and moved the logic for getting/generating them into that property method
- Improved the typing
- Included adding enums for `SkipStep`s and `DeployableResourceTypes`
- Added the new skip step logic for image uploads
- Added a new skip step type of `IMAGE_UPLOAD`
- No MyPy errors
- Following live tests
- `az aosm nfd publish -f input_files/input.json_nfd --definition-type vnf`
- `az aosm nfd publish -f input_files/input.json_nfd --definition-type vnf --skip image-upload`
- `az aosm nfd publish -f input_files/input.json_nfd --definition-type vnf --skip artifact-upload`
- `az aosm nfd …
=> Add skip steps, improve typing, stop passing variables around in method signatures

src/aosm/azext_aosm/_params.py, src/aosm/azext_aosm/custom.py, src/aosm/azext_aosm/deploy/deploy_with_arm.py, src/aosm/azext_aosm/util/constants.py
This is a small refactor to remove some duplicated code in the deploy_(x)nfd_from_bicep() methods.
The VNF And CNF versions shared a considerable amount of code. This has now been refactored out into a common method.
There was some associated tidying that came with this, such as removing a bizarrely garbled docblock for the former vnf method, and no longer passing around the configuration type as a method parameter.
I've moved the new _cnfd_artifact_upload() method to be immediately below the equivalent vnf method, which makes the changes look greater than they are. If that makes the review harder than it needs to be, I can show the reviewer the copy/paste to do to make the diff cleaner.
No testing done yet, I'll do it all after I've added the new "skip VHD upload" feature. This is a …
=> Dry the deploy_nfd_from_bicep() code

src/aosm/azext_aosm/tests/latest/test_aosm_vnf_publish_and_delete.py
The integration tests are broken when running from a recording. This is because of the bug in the CLI that causes the tests to time out. We should temporarily remove those tests to make sure all the other Unit tests can be run. 
---
=> Remove the integration test from the repo

src/aosm/azext_aosm/deploy/artifact.py
For running in environments without docker, such as CI pipelines. This affects uploading Helm charts for CNFs - the ACR login now fetches an access token, which is used to login to the Helm registry and upload the chart.
---
az aosm nfd publish
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but do not modify `src/index.json`. 
Fix for https://dev.azure.com/msazuredev/AzureForOperators/_workitems/ …
=> ADO-880627: Use docker-less ACR login

src/aosm/azext_aosm/_client_factory.py, src/aosm/azext_aosm/custom.py, src/aosm/azext_aosm/tests/latest/recordings/test_vnf_nsd_publish_and_delete.yaml, src/aosm/azext_aosm/tests/latest/test_nsd.py, src/aosm/azext_aosm/util/constants.py
https://dev.azure.com/msazuredev/AzureForOperators/_workitems/edit/895539
Anand has confirmed that it is only Allow-2023-09-01 which will be required come GA time. I do not propose adding this fix to the pre-release-add-aosm-extension branch, as it will be unhelpful pre-release
=> Check for Azure features on deploy and delete

src/aosm/azext_aosm/_configuration.py, src/aosm/azext_aosm/deploy/pre_deploy.py, src/aosm/azext_aosm/generate_nsd/nf_ret.py, src/aosm/azext_aosm/vendored_sdks/operations/_proxy_network_function_definition_versions_operations.py
* added publisher scope to input file; changed to proxy nsdv
* fixed get request on proxy nfdv (should be overwritten when autogenerated again)
* small print bug fix
---------
---
=> Jl/nfdv proxy (#73)

src/aosm/azext_aosm/_configuration.py
---
Temporary fix for bug [919007 ](https://msazuredev.visualstudio.com/AzureForOperators/_workitems/edit/919007).
Follow on story raised to handle all optional inputs in cli
Behaviour remains the same for:
- Providing source_registry and source_local_docker_image
- Providing source_registry but not source_registry_namespace
Fixed error for:
- Providing both source_registry, source_registry_namespace but not source_local_docker_image
We should revisit this fix when we do proper refactor of optional parameters in CLI.
az aosm nfd build --config-file input.json --definition-type cnf
Once your pull …
=> Fix source_local_docker_image defaults to placeholder text

src/aosm/azext_aosm/_configuration.py
* temp fix for bug
* minor formatting
* refactor + change validation ordering to mimic previous behaviour
* add docstring
---------
---
=> Fix source_local_docker_image defaults to placeholder text (#79)

src/aosm/azext_aosm/_configuration.py, src/aosm/azext_aosm/custom.py, src/aosm/azext_aosm/delete/delete.py, src/aosm/azext_aosm/deploy/deploy_with_arm.py, src/aosm/azext_aosm/deploy/pre_deploy.py
Cherry-pick "renamed nsdg to nsd" from main add-aosm-extension
=> renamed nsdg to nsd

src/aosm/azext_aosm/deploy/pre_deploy.py
One line fix to return True if all required artifact manifests exist, not just the last one checked.
=> Return True if _all_ required artifact manifests exist, not just the last one checked.

src/aosm/README.md, src/aosm/azext_aosm/util/constants.py
Revert accidental pre-release merge of https://github.com/jddarby/azure-cli-extensions/pull/71 but change it to check for the FF you need for pre-release. https://eng.ms/docs/strategic-missions-and-technologies/strategic-missions-and-technologies-organization/azure-for-operators/aiops/aiops-orchestration/aosm-product-docs/shared_infrastructure/ansm_onboarding 
Anand told me that the MsiForResourceEnabled one isn't required any more, so I am not checking for that one.
The GA release deliberately doesn't have the FF names listed in the README.md as Peter told me they are somehow "hidden" FF, and the customer shouldn't know their names, just to follow the onboarding docs.  The Pre-release ones I think are useful though.
I've tested this on our UK subscription.
=> Check pre release ff not ga

src/aosm/azext_aosm/_configuration.py, src/aosm/azext_aosm/custom.py, src/aosm/azext_aosm/deploy/deploy_with_arm.py, src/aosm/azext_aosm/deploy/pre_deploy.py, src/aosm/azext_aosm/generate_nfd/cnf_nfd_generator.py, src/aosm/azext_aosm/generate_nfd/vnf_nfd_generator.py, src/aosm/azext_aosm/generate_nsd/nf_ret.py, src/aosm/azext_aosm/generate_nsd/nsd_generator.py, src/aosm/azext_aosm/tests/latest/mock_nsd/input.json, src/aosm/azext_aosm/tests/latest/mock_nsd/input_multi_nf_nsd.json, src/aosm/azext_aosm/tests/latest/mock_nsd/input_multiple_instances.json, src/aosm/azext_aosm/tests/latest/scenario_test_mocks/mock_input_templates/cnf_nsd_input_template.json, src/aosm/azext_aosm/tests/latest/scenario_test_mocks/mock_input_templates/vnf_nsd_input_template.json
I've created explicit helptext commands on each of the configuration objects.  That means that we don't have to use the defaults for the helptext anymore, so can set actual defaults if we want to.  That also means that none of the validation/__post_init__ functions have to worry about fields being set to helptext strings.
I've also tidied up validation, such that all the validation commands are called in a cascading manner when we are ready, rather than in an adhoc manner from other functions.
The live publisher test is failing, but it is something to do with not finding a proxy publisher resource.  This is unrelated to this change and we are just about to remove the proxy publisher stuff, so I'm not going to worry about it for now.
=> Fix up helptext and validation to be a bit saner

src/aosm/azext_aosm/deploy/pre_deploy.py
Fix for https://dev.azure.com/msazuredev/AzureForOperators/_workitems/edit/912974
Revert bad markup made in https://github.com/jddarby/azure-cli-extensions/commit/b5372aa39abcc80ccb526a7a08d6a180d69f9979#diff-0e7574c90b51994437d69e1ac7a9b20d13c6074d5cbfc495ff82460de1e8207e 
Not tested because this used to work.
=> revert bad markup

src/aosm/azext_aosm/tests/latest/scenario_test_mocks/mock_input_templates/cnf_input_template.json, src/aosm/azext_aosm/tests/latest/scenario_test_mocks/mock_input_templates/cnf_nsd_input_template.json, src/aosm/azext_aosm/tests/latest/scenario_test_mocks/mock_input_templates/vnf_input_template.json, src/aosm/azext_aosm/tests/latest/scenario_test_mocks/mock_input_templates/vnf_nsd_input_template.json, src/aosm/azext_aosm/tests/latest/test_aosm_cnf_publish_and_delete.py, src/aosm/azext_aosm/tests/latest/test_aosm_vnf_publish_and_delete.py
Our live tests were using westcentralus. 
This region has been reserved for billing tests, and no one else should be deploying to it.
This PR moves our live tests to use uaenorth. This is intentionally _not_ uksouth, as developers often do their manual testing there, and this provides a little more regional coverage.
=> Move live tests to uaenorth

src/aosm/azext_aosm/deploy/artifact.py
Fix for ADO bug 922085.
If a publish command fails to push to an ACR, the error is logged out including the command used - which also includes the password in-line. It feels like a security hole waiting to happen to do this and not adequately warn customers that it will happen should they want to send out their logs to somewhere, which would inevitably lead to plaintext transmission of secrets and possible scope for leaks.
Therefore, remove the password from the log before outputting.
=> Don't log out ACR passwords when artifact commands fail

src/aosm/azext_aosm/deploy/artifact.py, src/aosm/azext_aosm/deploy/deploy_with_arm.py
https://github.com/jddarby/azure-cli-extensions/pull/72 introduced a bug for CNF image copy, where it only worked if the source and target ACR were in the same subscription.
Attempt 2 to fix this. Rejected attempt 1 was here: https://github.com/jddarby/azure-cli-extensions/pull/98
https://learn.microsoft.com/en-us/azure/container-registry/container-registry-import-images?tabs=azure-cli#import-from-a-registry-in-a-different-subscription explains the syntax for az acr import cross subscription and explains that this also works in the same subscription.
This fixes that by getting an access token for the current CLI user and using that as the password on the az acr import command.  This is documented as the way to access an ACR from a different tenant, but I've tested it and it also works for …
=> Fix cnf image take 2

src/aosm/azext_aosm/_configuration.py, src/aosm/azext_aosm/generate_nfd/cnf_nfd_generator.py
- Added default rg and acr values for nf + nsd based on publisher name
- Added blob_url default for VNF based on publisher name
- Updated helptext 
- Added fix for bug https://dev.azure.com/msazuredev/AzureForOperators/_workitems/edit/920284, as very minor change
Testing when no RG or ACR given:
- VNF no errors on build (did not try to test further)
- CNF no errors on build, successful publish of publisher, RG and ACR
- NSD: no errors on build, successful publish of all resources
Testing with both RG and ACR given:
- Tested with CNF and NSD, behaviour as before
---
Once your pull request is merged …
=> Default RG and ACR Values with Publisher Name

src/aosm/azext_aosm/generate_nfd/cnf_nfd_generator.py
Tom Salam wrote this but didn't have permissions to push.
Let me know if I should be doing any testing here.
When parsing a values.yaml file in the following format:
sasDiscovery:
- discovery: "<sas-value>"
In the mappyings.yaml file this was becoming the invalid:
sasDiscovery:
- discovery: '{deployParameters.sasDiscovery)_0_discovery}'
=> fix unexpected symbol when parsing lists

src/aosm/azext_aosm/generate_nfd/cnf_nfd_generator.py, src/aosm/azext_aosm/generate_nfd/templates/cnfdefinition.bicep.j2
Bugfix for https://dev.azure.com/msazuredev/AzureForOperators/_workitems/edit/928366
=> Validation requirements on helm names

src/aosm/azext_aosm/_configuration.py, src/aosm/azext_aosm/generate_nfd/vnf_nfd_generator.py, src/aosm/azext_aosm/tests/latest/mock_vnf/input_with_sas.json, src/aosm/azext_aosm/tests/latest/test_aosm_vnf_publish_and_delete.py, src/aosm/azext_aosm/tests/latest/test_vnf.py, src/aosm/azext_aosm/util/constants.py, src/aosm/azext_aosm/util/utils.py
This PR is to address two issues around the generated VHD parameters for the VNF build path:
1. Stop hard coding the value of `azureDeployLocation`. This value should always be configurable.
2. Add the following optional parameters to the VHD artifact configuration:
-  imageDiskSizeGB
- imageOsState
- imageOsType
- imageHyperVGeneration
- imageApiVersion
These values are set to defaults by NFM when they are not provided but it is necessary that we give publishers the option to configure them
I have also made the VNF publish and delete test a live test only. This is because it was causing issues for people when running the UTs doe to an underlying issue with the test framework. Please chat to Patryk for more context.
I am planning to merge this into the `add-aosm-extension` branch and then …
=> Image value mappings fixes

src/aosm/azext_aosm/_configuration.py, src/aosm/azext_aosm/deploy/artifact.py, src/aosm/azext_aosm/util/constants.py
---
Fixes for:
1) The input.json file created by running "az aosm nfd generate-config --definition-type vnf" says vhd version field should be in A.B.C format, but sample input-vnf-nfd.json and the variable/description talbe in the quickstart say A-B-C format.
2) The input file above also has blob_sas_uri for the arm template artifact, which is not relevant and doesn't work. 
Both these used to work so have been broken by something in the last few weeks. 
This PR:
- Removed blob_sas_url option + amended validation 
- Changed placeholder text (separated file_path under arm_template and vhd)
- Fixed help text for artifact versions
- Fixed validation for artifacts (arm vs vhd)
- Fixed minor comment typos
- minor formatting
NOT DONE - refactored ArtifactConfig to have a general ABC superclass …
=> Remove Blob_SAS_URL Option from ArmTemplate in input file

src/aosm/azext_aosm/cli_handlers/onboarding_cnf_handler.py, src/aosm/azext_aosm/cli_handlers/onboarding_vnf_handler.py, src/aosm/azext_aosm/definition_folder/builder/definition_folder_builder.py
1. There was a bug in the CLI where the JSON output was not formatted correctly for CNFs and for VNFs the output was escaped JSON:
This happened because in the first case we were just writing the string into a JSON file without any formatting, and in the other case we were trying to do formatting using `json.dumps` but on a string instead of a Python object. I added a `json.loads` call to change the string into a valid JSON object and then output that into the JSON file. 
2. Second bug was that we were never deleting our build file when telling the user we will overwrite it but instead we just overwrote individual files in that folder. I added a delete call. to make sure no temporary files are left in the folder. 
This PR includes some formatting changes. I think they are correct as I am …
=> Fix two minor CLI bugs

src/aosm/azext_aosm/cli_handlers/onboarding_base_handler.py, src/aosm/azext_aosm/cli_handlers/onboarding_nsd_handler.py, src/aosm/azext_aosm/cli_handlers/onboarding_vnf_handler.py, src/aosm/azext_aosm/common/artifact.py, src/aosm/azext_aosm/configuration_models/common_parameters_config.py, src/aosm/azext_aosm/configuration_models/onboarding_base_input_config.py, src/aosm/azext_aosm/configuration_models/onboarding_cnf_input_config.py, src/aosm/azext_aosm/configuration_models/onboarding_nfd_base_input_config.py, src/aosm/azext_aosm/configuration_models/onboarding_vnf_input_config.py, src/aosm/azext_aosm/definition_folder/builder/artifact_builder.py, src/aosm/azext_aosm/definition_folder/reader/artifact_definition.py, src/aosm/azext_aosm/inputs/helm_chart_input.py
=> Minor input improvements

src/aosm/azext_aosm/configuration_models/onboarding_base_input_config.py, src/aosm/azext_aosm/configuration_models/onboarding_cnf_input_config.py
=> edited input file

src/aosm/azext_aosm/cli_handlers/onboarding_base_handler.py, src/aosm/azext_aosm/custom.py
…separately; added better validation
---
=> Base handler treats command inputs separately

src/aosm/azext_aosm/build_processors/base_processor.py
---
- Quick fix in base processor to check for type and oneOf/anyOf
- Maybe this would be better before we get to the problem function (generate_value_mappings) but in the helm input we only load the schema, so it would be repeating the logic of iterating through each part of schema
=> Bug: No type in schema

src/aosm/azext_aosm/cli_handlers/onboarding_nexus_vnf_handler.py, src/aosm/azext_aosm/common/constants.py, src/aosm/azext_aosm/common/utils.py, src/aosm/azext_aosm/configuration_models/onboarding_vnf_input_config.py
---
- Added semver regex from [semver](https://semver.org/)
- Added semver validation to nexus image input config
- Moved split image path into utils
=> Bug: Nexus Image Version Must be Semver

src/aosm/azext_aosm/definition_folder/reader/definition_folder.py
---
- Used ResourceManagementClient to check for existence and then create RG
- Think it is done at a sensible time, during publish, but before each element.deploy
=> Create RG if it doesn't exist

src/aosm/azext_aosm/inputs/vhd_file_input.py
---
We need to convert our vhd parameters to camel case, so that it doesn't fail on the SNS put.
=> Template Parameters Bug

src/aosm/azext_aosm/build_processors/vhd_processor.py, src/aosm/azext_aosm/cli_handlers/onboarding_core_vnf_handler.py, src/aosm/azext_aosm/configuration_models/onboarding_vnf_input_config.py
To simplify the CLI, we are removing imageName from the deployParameters.
This means:
- remove image name parameter from config
- add imageName as default config + hardcode
---
=> Remove imageName from deployparameters

src/aosm/azext_aosm/build_processors/base_processor.py
=> Fix bool in schema bug

src/aosm/HISTORY.rst, src/aosm/setup.py
The Oras library we use has the Python docker module as an optional requirement. We do use that branch of Oras's code, so need the module.  We didn't have the optional requirement turned on, so if you didn't already have the Python docker module installed, the AOSM CLI broke.
This PR adds the docker option into setup.py.
Tobias Weiserth hit this. Confirmed fixed after this change.
---
You only need to update the version information in file setup.py and historical …
=> Add docker dependency option to oras in setup.py

src/aosm/azext_aosm/common/command_context.py, src/aosm/azext_aosm/common/exceptions.py, src/aosm/azext_aosm/definition_folder/builder/json_builder.py, src/aosm/azext_aosm/inputs/arm_template_input.py, src/aosm/azext_aosm/inputs/base_input.py, src/aosm/azext_aosm/tests/latest/unit_test/test_processors/test_core_arm_processor.py, src/aosm/azext_aosm/tests/latest/unit_test/test_processors/test_helm_chart_processor.py, src/aosm/azext_aosm/tests/latest/unit_test/test_processors/test_nexus_arm_processor.py
---
added license headers to fix release jobs
=> Fix Missing License Headers

src/aosm/HISTORY.rst, src/aosm/azext_aosm/aaz/latest/aosm/__cmd_group.py, src/aosm/azext_aosm/aaz/latest/aosm/publisher/__cmd_group.py, src/aosm/azext_aosm/aaz/latest/aosm/publisher/artifact_manifest/__cmd_group.py, src/aosm/azext_aosm/aaz/latest/aosm/publisher/artifact_manifest/_list.py, src/aosm/azext_aosm/aaz/latest/aosm/publisher/artifact_manifest/_list_credential.py, src/aosm/azext_aosm/aaz/latest/aosm/publisher/artifact_manifest/_update_state.py, src/aosm/azext_aosm/aaz/latest/aosm/publisher/artifact_store/artifact/_list.py, src/aosm/azext_aosm/aaz/latest/aosm/publisher/artifact_store/artifact/version/_list.py, src/aosm/azext_aosm/aaz/latest/aosm/publisher/artifact_store/artifact/version/_update_state.py, src/aosm/azext_aosm/aaz/latest/aosm/publisher/configuration_group_schema/_list.py, src/aosm/azext_aosm/aaz/latest/aosm/publisher/configuration_group_schema/_update_state.py, src/aosm/azext_aosm/aaz/latest/aosm/publisher/network_function_definition/version/_list.py, src/aosm/azext_aosm/aaz/latest/aosm/publisher/network_function_definition/version/_update_state.py, src/aosm/azext_aosm/aaz/latest/aosm/publisher/network_service_design/version/_list.py, src/aosm/azext_aosm/aaz/latest/aosm/publisher/network_service_design/version/_update_state.py, src/aosm/azext_aosm/common/constants.py, src/aosm/azext_aosm/configuration_models/onboarding_cnf_input_config.py, src/aosm/azext_aosm/custom.py, src/aosm/azext_aosm/definition_folder/reader/bicep_definition.py, src/aosm/azext_aosm/inputs/helm_chart_input.py, src/aosm/azext_aosm/tests/latest/integration_tests/scenario_tests/recordings/test_cnf_nfd_build_and_publish.yaml, src/aosm/azext_aosm/tests/latest/integration_tests/scenario_tests/recordings/test_vnf_nsd_build_and_publish.yaml, src/aosm/azext_aosm/tests/latest/unit_test/test_definiton_folder_builder/test_bicep_definition.py
---
----------
https://dev.azure.com/msazuredev/AzureForOperators/_workitems/edit/1161413
------------
-----------
--------
=> Adding a validation to check if base resources are already deployed.

src/aosm/HISTORY.rst, src/aosm/azext_aosm/cli_handlers/onboarding_nsd_handler.py
---
Problem:
When multiple nf RETs were defined in nsd-input.jsonc, there would be 2 RETs in the NSDV but they would be identical, there would also only be one mapping file. This was due to the previous design decision to call the RETs the NSD name and version, instead of the NF name.
Fix:
- Changed processor and artifacts to use nf name instead of nsd name
Testing:
- Testing single nf still behaves as expected with cnf to sns - ongoing
- Test NSDV republish with same values
- Test NSDV republish with different values
- Test multi nf to sns with 2 CNFS:
- 
Once your pull request is merged into …
=> Fix Multi-NF failure

src/aosm/setup.py
Straightforward security bump.
Jinja2 release notes here: https://github.com/pallets/jinja/releases
Low risk, and no testing done.
=> Bump jinja2 to 3.1.4.

src/aosm/azext_aosm/tests/latest/integration_tests/scenario_tests/test_aosm_vnf_build_and_publish.py
Make the vnf test live to avoid `CannotOverwriteExistingCassetteException`
=> Make the vnf test live only
